### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by TheSableCZ** [Crabstering/Hotelenky-Api#4]
Po několika hotelech vyhodí hlášku. Možná druhý request? Nevím. Ale u CZ to nedostahuje ani Prahu.
Hotelbeds mi asi na tenhle dotaz ukazuje 2 requesty.
<img width="1270" alt="snimek obrazovky 2018-07-20 v 18 34 48" src="https://user-images.githubusercontent.com/6191242/43014260-ddf330be-8c4b-11e8-995f-97dcc3750997.png">

```
(node:33979) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at countryInList.(anonymous function).cities.some (/Users/jan/Dropbox/js/Hotelenky-API/Hotelenky-Api/express-test/index.js:71:60)
    at Array.some (<anonymous>)
    at CountryHotel.find.exec.then (/Users/jan/Dropbox/js/Hotelenky-API/Hotelenky-Api/express-test/index.js:66:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:33979) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33979) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by writecz** [comment]
Kluci to vypadá na ten limit 50, sjíždíte to moc rychle nebo hledání nic
nevrací.

Dne pá 20. 7. 2018 18:42 uživatel Jan Sobol <notifications@github.com>
napsal:

**Comment by TheSableCZ** [comment]
Díky :) To je dost možný, protože je tam limit 2 dotazy za sekundu.

**Comment by writecz** [comment]
Já to dělám tak, že zavolám další request se zpožděním pres sleep az v
navratove funkci předchozího, je to nejjednodušší. Samo jsem zkoušel i
promise a async, ale to bývá ukecanejsi...

Dne pá 20. 7. 2018 18:50 uživatel Jan Sobol <notifications@github.com>
napsal:
